### PR TITLE
Ansible Role - Transition from Username/Password to Token Auth for TPP

### PR DESCRIPTION
**Pull request by angelmoo**
Added the capability to user access token for tpp server

all test suite passed

### CODE REVIEW

**Review by tr1ck3r — APPROVED** [review]
Looks good to me

**Comment by achuchev** [comment]
@angelmoo I just noticed that the examples in the readme are still using username/password. Maybe, it will be better if token is used.

**Comment by tr1ck3r** [comment]
@achuchev agreed.  We intentionally excluded the README from this because we're expecting a major doc revision to be delivered by the Venafi SA/PS teams.  If they're not able to deliver it in a timely manner, I will make incremental updates to the existing README after I've completed my acceptance testing and generated a release candidate.

**Review by LanceGardiner-VEN — APPROVED** [review]
checks out

**Pull request merged**
